@startuml

hide circle
skinparam linetype ortho

entity "Usuario" as Usuario {
  +id_usuario : INT <<PK>>
  nome : VARCHAR(100)
  email : VARCHAR(100)
  senha_hash : VARCHAR(255)
  tipo : ENUM('autor', 'avaliador', 'coordenador')
  area_atuacao : VARCHAR(100)
  afiliacao : VARCHAR(150)
  data_cadastro : DATETIME
}

entity "Evento" as Evento {
  +id_evento : INT <<PK>>
  nome : VARCHAR(150)
  descricao : TEXT
  banner_url : VARCHAR(255)
  data_inicio : DATE
  data_fim : DATE
  prazo_submissao_inicial : DATE
  prazo_avaliacao : DATE
  prazo_submissao_final : DATE
  local : VARCHAR(150)
  organizador_id : INT <<FK>>
}

entity "Artigo" as Artigo {
  +id_artigo : INT <<PK>>
  titulo : VARCHAR(200)
  resumo : TEXT
  palavras_chave : VARCHAR(255)
  area_tematica : VARCHAR(100)
  arquivo_pdf_inicial : VARCHAR(255)
  arquivo_pdf_final : VARCHAR(255)
  status : ENUM
  data_submissao : DATETIME
  id_evento : INT <<FK>>
}

entity "Artigo_Autor" {
  +id_artigo : INT <<FK>>
  +id_usuario : INT <<FK>>
  ordem_autoria : INT
}

entity "Avaliacao" {
  +id_avaliacao : INT <<PK>>
  id_artigo : INT <<FK>>
  id_avaliador : INT <<FK>>
  metodo : ENUM('double-blind')
  nota : DECIMAL(3,1)
  parecer : TEXT
  comentario_autor : TEXT
  comentario_coordenador : TEXT
  recomendacao : ENUM('aprovar', 'revisar', 'rejeitar')
  data_avaliacao : DATETIME
}

entity "Checklist_Avaliacao" {
  +id_checklist : INT <<PK>>
  id_avaliacao : INT <<FK>>
  criterio : VARCHAR(150)
  nota : INT
}

entity "Publicacao" {
  +id_publicacao : INT <<PK>>
  id_artigo : INT <<FK>>
  url_publicacao : VARCHAR(255)
  doi : VARCHAR(100)
  data_publicacao : DATE
}

entity "Anais" {
  +id_anais : INT <<PK>>
  id_evento : INT <<FK>>
  formato : ENUM('PDF', 'HTML')
  arquivo_url : VARCHAR(255)
  data_geracao : DATE
}

entity "Revisao_Artigo" {
  +id_revisao : INT <<PK>>
  id_artigo : INT <<FK>>
  versao : INT
  tipo : ENUM('inicial', 'revisada')
  arquivo_pdf : VARCHAR(255)
  data_envio : DATETIME
  observacao : TEXT
}


' RELACIONAMENTOS
Usuario ||--o{ Evento : organiza >
Evento ||--o{ Artigo : recebe >
Usuario ||--o{ Artigo_Autor : escreve >
Artigo ||--o{ Artigo_Autor : tem >
Artigo ||--o{ Avaliacao : é avaliado em >
Usuario ||--o{ Avaliacao : revisa >
Artigo ||--|| Publicacao : publicado como >
Avaliacao ||--o{ Checklist_Avaliacao : detalha >
Evento ||--o{ Anais : compila >
Artigo ||--o{ Revisao_Artigo : possui >

@enduml
